

const TAPESIZE: usize = 2048;
struct Tape {
    tape: [usize; TAPESIZE],
    position: usize,
}

fn get(tape: &Tape) -> usize {
    tape.tape[tape.position]
}

fn set(tape: &mut Tape, val: usize) {
    tape.tape[tape.position] = val
}

fn inc(tape: &mut Tape) {
    tape.tape[tape.position] += 1;
}

fn dec(tape: &mut Tape) {
    tape.tape[tape.position] -= 1;
}

fn advance(tape: &mut Tape) {
    tape.position += 1;
}

fn devance(tape: &mut Tape) {
    tape.position -= 1;
}


const EXIT: usize = 0;
const GET: usize = 1;
const SET: usize = 2;
const INC: usize = 3;
const DEC: usize = 4;
const ADV: usize = 5;
const DEV: usize = 6;
const PRINT: usize = 7;
const OUT: usize = 8;
const JFF: usize = 9;
const JTB: usize = 10;

fn __print(n: usize) { /*println!("{:?}", n);*/}
fn __out(n: usize) {}

fn __met_merge_point(n: usize) {}


fn main() {
    let mut tape = Tape { tape: [0; TAPESIZE], position: 0 };

    let mut pc = 0;

    //hello world
    // let program = [INC, INC, INC, INC, INC, INC, INC, INC, JFF + 768, ADV, INC, INC, INC, INC, JFF + 528, ADV, INC, INC, ADV, INC, INC, INC, ADV, INC, INC, INC, ADV, INC, DEV, DEV, DEV, DEV, DEC, JTB + 224, ADV, INC, ADV, INC, ADV, DEC, ADV, ADV, INC, JFF + 720, DEV, JTB + 688, DEV, DEC, JTB + 128, ADV, ADV, PRINT, ADV, DEC, DEC, DEC, PRINT, INC, INC, INC, INC, INC, INC, INC, PRINT, PRINT, INC, INC, INC, PRINT, ADV, ADV, PRINT, DEV, DEC, PRINT, DEV, PRINT, INC, INC, INC, PRINT, DEC, DEC, DEC, DEC, DEC, DEC, PRINT, DEC, DEC, DEC, DEC, DEC, DEC, DEC, DEC, PRINT, ADV, ADV, INC, PRINT, ADV, INC, INC, PRINT, EXIT];

    //print 2
    // let program = [INC, INC, OUT, EXIT];

    //for i in 10..1: print i
    // let program = [INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 208, OUT, DEC, JTB + 160, OUT, EXIT];

    //99 bottles
    let program = [ADV, INC, INC, INC, INC, INC, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 448, DEV, INC, INC, INC, INC, INC, ADV, DEC, JTB + 304, INC, INC, INC, INC, INC, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 896, DEV, INC, INC, INC, INC, INC, ADV, DEC, JTB + 752, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 1520, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 1392, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 1952, DEV, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 1776, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 2400, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 2176, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 2928, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 2768, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 3456, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 3296, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 3888, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 3680, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 4320, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 4096, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 4832, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 4672, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 5120, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 4992, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 5568, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 5344, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 6016, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 5792, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 6304, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 6176, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 6736, DEV, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 6560, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 7168, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 6944, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 7600, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 7376, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 8096, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 7936, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 8384, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 8256, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 8832, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 8608, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 9264, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 9040, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 9552, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 9424, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 10080, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 9920, INC, INC, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 10560, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 10336, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 10992, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 10768, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 11280, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 11152, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 11760, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 11552, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 12192, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 12000, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 12624, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 12416, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 13056, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 12848, ADV, INC, INC, INC, INC, INC, JFF + 13264, DEV, INC, INC, ADV, DEC, JTB + 13168, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 13792, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 13632, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 14224, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 14032, INC, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 14704, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 14512, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 15136, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 14912, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 15424, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 15296, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 15872, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 15648, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 16304, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 16080, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 16736, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 16512, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 17024, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 16896, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 17440, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 17216, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 17888, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 17664, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 18368, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 18160, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 18800, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 18576, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 19088, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 18960, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 19520, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 19328, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 19952, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 19728, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 20368, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 20144, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 20656, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 20528, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 21120, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 20896, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 21552, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 21360, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 22064, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 21904, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 22576, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 22416, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 22864, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 22736, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 23312, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 23120, INC, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 23840, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 23680, ADV, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 24128, DEV, INC, INC, INC, INC, ADV, DEC, JTB + 24000, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 24560, DEV, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 24368, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 25056, DEV, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 24896, INC, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 25504, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 25280, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 25952, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 25744, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 26384, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 26160, ADV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 26800, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, ADV, DEC, JTB + 26576, ADV, INC, INC, INC, INC, INC, JFF + 27008, DEV, INC, INC, ADV, DEC, JTB + 26912, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, JFF + 27264, DEV, JTB + 27232, ADV, ADV, ADV, ADV, JFF + 33344, DEV, JFF + 31712, JFF + 27424, ADV, JTB + 27392, DEV, DEV, PRINT, PRINT, JFF + 27536, DEV, JTB + 27504, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 28608, DEV, JTB + 28576, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 30544, DEV, JTB + 30512, ADV, ADV, DEC, DEV, PRINT, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 31632, DEV, JTB + 31600, ADV, ADV, ADV, DEC, JTB + 27376, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, DEV, INC, INC, INC, INC, INC, INC, INC, INC, INC, INC, DEV, DEC, JFF + 32128, ADV, JTB + 32096, DEV, PRINT, JFF + 32208, DEV, JTB + 32176, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 33248, DEV, JTB + 33216, ADV, ADV, ADV, ADV, DEC, JTB + 27344, INC, DEV, DEC, DEC, JFF + 37680, JFF + 33472, ADV, JTB + 33440, DEV, DEV, PRINT, PRINT, JFF + 33584, DEV, JTB + 33552, ADV, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 34640, DEV, JTB + 34608, ADV, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 36560, DEV, JTB + 36528, ADV, ADV, DEC, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 37600, DEV, JTB + 37568, ADV, ADV, ADV, DEC, JTB + 33424, INC, JFF + 37744, ADV, JTB + 37712, DEV, PRINT, JFF + 37824, DEV, JTB + 37792, ADV, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, DEV, DEV, DEV, DEV, PRINT, JFF + 38912, ADV, JTB + 38880, DEV, DEV, PRINT, PRINT, JFF + 39024, DEV, JTB + 38992, ADV, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 40064, DEV, JTB + 40032, ADV, ADV, PRINT, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, JFF + 41968, ADV, JTB + 41936, DEV, DEV, DEV, DEV, PRINT, DEV, DEV, PRINT, DEV, DEV, DEV, PRINT, JFF + 42208, DEV, JTB + 42176, ADV, ADV, ADV, ADV, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, ADV, PRINT, EXIT];

    loop {
        let code = program[pc];
        __met_merge_point(pc);

        if code == EXIT {
            break;
        } else if code == SET {

        } else if code == INC {
            inc(&mut tape);
        } else if code == DEC {
            dec(&mut tape);
        } else if code == ADV {
            advance(&mut tape);
        } else if code == DEV {
            devance(&mut tape);
        } else if code == PRINT {
            __print(get(&mut tape));
       } else if code == OUT {
            __out(get(&mut tape));
        } else if (code & 0xF) == JFF { //[
            if get(&tape) == 0 {
                pc = code >> 4usize;
            }
        } else if (code & 0xF) == JTB { //]
            if get(&tape) != 0 {
                pc = code >> 4usize;
            }
        }

        pc += 1;
    }
}